Electronic Bank/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Electronic_Bank.Data;
using Electronic_Bank.Models;

namespace Electronic_Bank.Controllers
{
    public class ClientsController : Controller
    {
        private readonly ElectronicBankContext _context;

        public ClientsController(ElectronicBankContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return _context.Clients != null ?
                        View(await _context.Clients.ToListAsync()) :
                        Problem("Entity set 'ElectronicBankContext.Clients'  is null.");
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.currancy = _context.Currencys;
           // ViewBag.currancy = new SelectList(_context.Currencys, "CurrencyID", "CurrencyCode");


            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            if (_context.Wallets != null)
            {
                //*****************************************\\
                foreach (var item in _context.Wallets)
                {

                    var clientWallets = await _context.Wallets
                                 .FirstOrDefaultAsync(m => (m.ClientID == id));

                    if (clientWallets != null)
                    {
                        client.ClientWallets.Add(clientWallets);

                    }

                }
            }
            //*****************************************\\

            return View(client);
        }



        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientID,ClientName,ClientAddress,ClientPhone,ClientImg")] Client client)
        {
            //if (ModelState.IsValid)
            //{

       //     client.ClientImg = "~/images/ProfileImage/" + client.ClientImg;
            _context.Add(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            //}
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientID,ClientName,ClientAddress,ClientPhone,ClientImg")] Client client)
        {
            if (id != client.ClientID)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
            try
            {
                _context.Update(client);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClientExists(client.ClientID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
            //}
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clients == null)
            {
                return Problem("Entity set 'ElectronicBankContext.Clients'  is null.");
            }
            var client = await _context.Clients.FindAsync(id);
            if (client != null)
            {
                _context.Clients.Remove(client);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return (_context.Clients?.Any(e => e.ClientID == id)).GetValueOrDefault();
        }

        public async Task<String> CurrencyCodeFind(int? CurrencyId)
        {
            var Currency1 = await _context.Currencys
   .FirstOrDefaultAsync(m => m.CurrencyID == CurrencyId);

            return Currency1.CurrencyCode;
        }

    }
}

Electronic Bank/Controllers/WalletsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Electronic_Bank.Data;
using Electronic_Bank.Models;

namespace Electronic_Bank.Controllers
{
    public class WalletsController : Controller
    {
        private readonly ElectronicBankContext _context;

        public WalletsController(ElectronicBankContext context)
        {
            _context = context;
        }

        // GET: Wallets
        public async Task<IActionResult> Index()
        {
            var electronicBankContext = _context.Wallets.Include(w => w.Clients).Include(w => w.Currencys);
            return View(await electronicBankContext.ToListAsync());
        }

        // GET: Wallets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Wallets == null)
            {
                return NotFound();
            }

            var wallet = await _context.Wallets
                .Include(w => w.Clients)
                .Include(w => w.Currencys)
                .FirstOrDefaultAsync(m => m.WalletID == id);
            if (wallet == null)
            {
                return NotFound();
            }

            return View(wallet);
        }

        // GET: Wallets/Create
        public async Task<IActionResult> Create(int? id)
        {
            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            ViewData["ClientID"] = id;
            ViewData["CurrencyID"] = new SelectList(_context.Currencys, "CurrencyID", "CurrencyName");
            return View();
        }

        // POST: Wallets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WalletID,WalletAmount,ClientID,CurrencyID")] Wallet wallet)
        {
            //if (ModelState.IsValid)
            //{
            _context.Add(wallet);

            //}
            ViewData["ClientID"] = new SelectList(_context.Clients, "ClientID", "ClientID", wallet.ClientID);
            ViewData["CurrencyID"] = new SelectList(_context.Currencys, "CurrencyID", "CurrencyID", wallet.CurrencyID);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            return View(wallet);
        }

        // GET: Wallets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Wallets == null)
            {
                return NotFound();
            }

            var wallet = await _context.Wallets.FindAsync(id);
            if (wallet == null)
            {
                return NotFound();
            }
            ViewData["ClientID"] = new SelectList(_context.Clients, "ClientID", "ClientName", wallet.ClientID);
            ViewData["CurrencyID"] = new SelectList(_context.Currencys, "CurrencyID", "CurrencyName", wallet.CurrencyID);
            return View(wallet);
        }

        // POST: Wallets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WalletID,WalletAmount,ClientID,CurrencyID")] Wallet wallet)
        {
            if (id != wallet.WalletID)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
            try
            {
                _context.Update(wallet);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!WalletExists(wallet.WalletID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
            //}
            ViewData["ClientID"] = new SelectList(_context.Clients, "ClientID", "ClientID", wallet.ClientID);
            ViewData["CurrencyID"] = new SelectList(_context.Currencys, "CurrencyID", "CurrencyID", wallet.CurrencyID);
            return View(wallet);
        }

        // GET: Wallets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Wallets == null)
            {
                return NotFound();
            }

            var wallet = await _context.Wallets
                .Include(w => w.Clients)
                .Include(w => w.Currencys)
                .FirstOrDefaultAsync(m => m.WalletID == id);
            if (wallet == null)
            {
                return NotFound();
            }

            return View(wallet);
        }

        // POST: Wallets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Wallets == null)
            {
                return Problem("Entity set 'ElectronicBankContext.Wallets'  is null.");
            }
            var wallet = await _context.Wallets.FindAsync(id);
            if (wallet != null)
            {
                _context.Wallets.Remove(wallet);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WalletExists(int id)
        {
            return (_context.Wallets?.Any(e => e.WalletID == id)).GetValueOrDefault();
        }


    }
}

Electronic Bank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Electronic_Bank</title>
	@*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Electronic_Bank.styles.css" asp-append-version="true" />*@

	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/materialdesignicons.min.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/materialdesignicons.min.css.map" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/style.css.map" asp-append-version="true" />
	<link rel="stylesheet" href="~/lib/fontawsoms/css/fontawesome-iconpicker.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/all.min.css" asp-append-version="true" />





</head>
<body>

	<div class="container-scroller">
		<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
			<div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
				<a class="navbar-brand brand-logo" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.svg" alt="logo" /></a>
				<a class="navbar-brand brand-logo-mini" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo-mini.svg" alt="logo" /></a>
			</div>
			<div class="navbar-menu-wrapper d-flex align-items-stretch">
				<button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
					<span class="mdi mdi-menu"></span>
				</button>
				<div class="search-field d-none d-md-block">
					<form class="d-flex align-items-center h-100" action="#">
						<div class="input-group">
							<div class="input-group-prepend bg-transparent">
								<i class="input-group-text border-0 mdi mdi-magnify"></i>
							</div>
							<input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
						</div>
					</form>
				</div>
				<ul class="navbar-nav navbar-nav-right">
					<li class="nav-item d-none d-lg-block full-screen-link">
						<a class="nav-link">
							<i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
						</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="mdi mdi-email-outline"></i>
							<span class="count-symbol bg-warning"></span>
						</a>
						<div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
							<h6 class="p-3 mb-0">Messages</h6>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item preview-item">
								<div class="preview-thumbnail">
									<img src="~/images/faces/face4.jpg" alt="image" class="profile-pic">
								</div>
								<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
									<h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
									<p class="text-gray mb-0"> 1 Minutes ago </p>
								</div>
							</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item preview-item">
								<div class="preview-thumbnail">
									<img src="~/images/faces/face4.jpg" alt="image" class="profile-pic">
								</div>
								<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
									<h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
									<p class="text-gray mb-0"> 15 Minutes ago </p>
								</div>
							</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item preview-item">
								<div class="preview-thumbnail">
									<img src="~/images/faces/face3.jpg" alt="image" class="profile-pic">
								</div>
								<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
									<h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
									<p class="text-gray mb-0"> 18 Minutes ago </p>
								</div>
							</a>
							<div class="dropdown-divider"></div>
							<h6 class="p-3 mb-0 text-center">4 new messages</h6>
						</div>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-bs-toggle="dropdown">
							<i class="mdi mdi-bell-outline"></i>
							<span class="count-symbol bg-danger"></span>
						</a>
						<div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
							<h6 class="p-3 mb-0">Notifications</h6>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item preview-item">
								<div class="preview-thumbnail">
									<div class="preview-icon bg-success">
										<i class="mdi mdi-calendar"></i>
									</div>
								</div>
								<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
									<h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
									<p class="text-gray ellipsis mb-0"> Just a reminder that you have an event today </p>
								</div>
							</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item preview-item">
								<div class="preview-thumbnail">
									<div class="preview-icon bg-warning">
										<i class="mdi mdi-settings"></i>
									</div>
								</div>
								<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
									<h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
									<p class="text-gray ellipsis mb-0"> Update dashboard </p>
								</div>
							</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item preview-item">
								<div class="preview-thumbnail">
									<div class="preview-icon bg-info">
										<i class="mdi mdi-link-variant"></i>
									</div>
								</div>
								<div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
									<h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
									<p class="text-gray ellipsis mb-0"> New admin wow! </p>
								</div>
							</a>
							<div class="dropdown-divider"></div>
							<h6 class="p-3 mb-0 text-center">See all notifications</h6>
						</div>
					</li>
					<li class="nav-item nav-logout d-none d-lg-block">
						<a class="nav-link" href="#">
							<i class="mdi mdi-power"></i>
						</a>
					</li>
					<li class="nav-item nav-settings d-none d-lg-block">
						<a class="nav-link" href="#">
							<i class="mdi mdi-format-line-spacing"></i>
						</a>
					</li>
				</ul>
				<button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
					<span class="mdi mdi-menu"></span>
				</button>
			</div>
		</nav>

		<div class="container-fluid page-body-wrapper">
			<!-- partial:partials/_sidebar.html -->
			<nav class="sidebar sidebar-offcanvas" id="sidebar">
				<ul class="nav">

					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="Clients" asp-action="Index">
							<span class="menu-title">Clients</span>
							<i class="mdi mdi-account menu-icon"></i>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="Wallets" asp-action="Index">
							<span class="menu-title">Wallets</span>
							<i class="mdi mdi-wallet menu-icon"></i>
							
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="currencies" asp-action="Index">
							<span class="menu-title">currencies</span>
							<i class="mdi mdi-currency-btc menu-icon"></i>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="Transactions" asp-action="Index">
							<span class="menu-title">Transactions</span>
							<i class="mdi mdi-table-large menu-icon"></i>
						</a>
					</li>

					<li class="nav-item sidebar-actions">
						<span class="nav-link">
							<div class="border-bottom">
								<h6 class="font-weight-normal mb-3">Projects</h6>
							</div>
							<button class="btn btn-block btn-lg btn-gradient-primary mt-4">+ Add a project</button>
							<div class="mt-4">
								<div class="border-bottom">
									<p class="text-secondary">Categories</p>
								</div>
								<ul class="gradient-bullet-list mt-4">
									<li>Free</li>
									<li>Pro</li>
								</ul>
							</div>
						</span>
					</li>
				</ul>
			</nav>
			<div class="main-panel">

				<main role="main" class="pb-3">
					@RenderBody()
				</main>
			</div>

			<!-- partial -->
			<!-- main-panel ends -->
		</div>


		@*	<div class="container">

		</div>*@

		<footer class="footer">
			<div class="container-fluid d-flex justify-content-between">
				<span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © bootstrapdash.com 2021</span>
				<span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin template</a> from Bootstrapdash.com</span>
			</div>
		</footer>
	</div>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)






	@***************************************************************@



	<script src="~/js/jquery.cookie.js" asp-append-version="true"></script>
	<script src="~/js/off-canvas.js" asp-append-version="true"></script>
	<script src="~/js/hoverable-collapse.js" asp-append-version="true"></script>
	<script src="~/js/misc.js" asp-append-version="true"></script>
	<script src="~/js/dashboard.js" asp-append-version="true"></script>
	<script src="~/js/todolist.js" asp-append-version="true"></script>
	<script src="~/js/Chart.min.js" asp-append-version="true"></script>
	<script src="~/js/vendor.bundle.base.js" asp-append-version="true"></script>
	@*<script src="~/lib/fontawsoms/js/fontawesome-iconpicker.js" asp-append-version="true"></script>*@
	@*<script src="~/lib/fontawsoms/js/fontawesome-iconpicker.min.js" asp-append-version="true"></script>*@
	<script src="~/js/all.min.js" asp-append-version="true"></script>



	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>